# action.yml
name: 'CI PHP Vendors'
description: 'Install PHP vendors through composer'
runs:
  using: 'docker'
  image: 'docker://allopneus/ci-php-actions'
  args:
    - echo "::set-output name=dir::$(composer config cache-files-dir)" && \
      composer global require hirak/prestissimo && \
      composer install --no-progress --no-suggest --prefer-dist --no-scripts
